Avoid compiler error on VS6 (#2092)
VS6 errors with compiler error
```
error C2520: conversion from unsigned __int64 to double not implemented, use signed __int64
```

which simply can be avoided if unsigned int64 type is disabled (by macro HAVE_MATIO_UINT64_T). Thus, if someone really wants to read an unsigned int64 array from a MAT file, a later VS compiler needs to be used.